name: Publish to MavenCentral

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'   

jobs:
  publish:
    name: Publish to MavenCentral
    runs-on: ubuntu-latest

    steps:
 
      - uses: actions/checkout@v3

  
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

  
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

 
      - name: Build and Publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }} 
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }} 
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }} 
          GITHUB_TOKEN: ${{ secrets.LIB_TOKEN }}
          VERSION_NAME: ${{ env.VERSION }}
        run: |
          ./gradlew publishToSonatype closeSonatypeStagingRepository --info
